backend:
  name: git-gateway
  branch: Guildford

media_folder: "hugo/static/assets/uploads"
public_folder: "assets/uploads"

collections:
  - name: "pages"
    label: "Pages"
    editor:
      preview: false
    files:
      - file: "hugo/content/_index.md"
        label: "Home"
        name: "home"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Header", name: "header", widget: "object", fields: [
              {label: "Background (optional)", name: "background", widget: "image"},
              {label: "Classes", name: "classes", widget: "hidden", default: "home-header"},
              {label: "Header Text (optional)", name: "hero", widget: "markdown"}
            ]}
          - {label: "What Is", name: "whatis", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Body", name: "body", widget: "markdown"},
              {label: "Button", name: "button", widget: "object", fields: [
                {label: "URL (inc. http://)", name: "url", widget: "string"},
                {label: "Text", name: "text", widget: "string"}
              ]},
              {label: "Image", name: "image", widget: "image"}
            ]}
          - {label: "Who", name: "who", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Body", name: "body", widget: "markdown"}
            ]}
          - {label: "How", name: "how", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Body", name: "body", widget: "markdown"}
            ]}
          - {label: "Partners", name: "partners", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "YouTube (embed URL)", name: "youtube", widget: "string"},
              {label: "Image (only set if no YouTube)", name: "image", widget: "image"},
              {label: "Body", name: "body", widget: "markdown"},
              {label: "List", name: "list", widget: "markdown"}
            ]}
      - file: "hugo/content/how-it-works/_index.md"
        label: "How it Works"
        name: "how-it-works"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Header", name: "header", widget: "object", fields: [
              {label: "Background (optional)", name: "background", widget: "image"},
              {label: "Header Text (optional)", name: "hero", widget: "markdown"}
            ]}
          - {label: "Intro", name: "intro", widget: "object", fields: [
              {label: "Body", name: "body", widget: "markdown"},
              {label: "Button", name: "button", widget: "object", fields: [
                {label: "URL (inc. http://)", name: "url", widget: "string"},
                {label: "Text", name: "text", widget: "string"}
              ]}
            ]}
          - {label: "Where", name: "where", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Body", name: "body", widget: "markdown"},
              {label: "Image", name: "image", widget: "image"},
              {label: "Stat 1", name: "stat1", widget: "object", fields: [
                {label: "Image", name: "image", widget: "image"},
                {label: "Count", name: "count", widget: "string"},
                {label: "Text", name: "text", widget: "string"}
              ]},
              {label: "Stat 2", name: "stat2", widget: "object", fields: [
                {label: "Image", name: "image", widget: "image"},
                {label: "Count", name: "count", widget: "string"},
                {label: "Text", name: "text", widget: "string"}
              ]},
              {label: "Stat 3", name: "stat3", widget: "object", fields: [
                {label: "Image", name: "image", widget: "image"},
                {label: "Count", name: "count", widget: "string"},
                {label: "Text", name: "text", widget: "string"}
              ]}
            ]}
          - {label: "How", name: "how", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Body", name: "body", widget: "markdown"},
              {label: "Card 1", name: "card1", widget: "object", fields: [
                {label: "Heading", name: "heading", widget: "string"},
                {label: "Subheading", name: "subheading", widget: "string"},
                {label: "Body", name: "body", widget: "markdown"}
              ]},
              {label: "Card 2", name: "card2", widget: "object", fields: [
                {label: "Heading", name: "heading", widget: "string"},
                {label: "Subheading", name: "subheading", widget: "string"},
                {label: "Body", name: "body", widget: "markdown"}
              ]},
              {label: "Button", name: "button", widget: "object", fields: [
                {label: "URL (inc. http://)", name: "url", widget: "string"},
                {label: "Text", name: "text", widget: "string"}
              ]}
            ]}
      - file: "hugo/content/how-to-apply/_index.md"
        label: "How to Apply"
        name: "how-to-apply"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Header", name: "header", widget: "object", fields: [
              {label: "Background (optional)", name: "background", widget: "image"},
              {label: "Header Text (optional)", name: "hero", widget: "markdown"}
            ]}
          - {label: "Body", name: "content", widget: "markdown"}
          - {label: "List", name: "list", widget: "markdown"}
          - {label: "Partners", name: "partners", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "body", name: "body", widget: "markdown"}
            ]}
      - file: "hugo/content/get-involved/_index.md"
        label: "Get Involved"
        name: "get-involved"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Header", name: "header", widget: "object", fields: [
              {label: "Background (optional)", name: "background", widget: "image"},
              {label: "Header Text (optional)", name: "hero", widget: "markdown"}
            ]}
          - {label: "Body", name: "content", widget: "markdown"}
          - {label: "Section", name: "section", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Body", name: "body", widget: "markdown"},
              {label: "Image", name: "image", widget: "image"}
            ]}
      - file: "hugo/content/privacy/_index.md"
        label: "Privacy Policy"
        name: "privacy"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Header", name: "header", widget: "object", fields: [
              {label: "Background (optional)", name: "background", widget: "image"},
              {label: "Header Text (optional)", name: "hero", widget: "markdown"}
            ]}
          - {label: "Body", name: "content", widget: "markdown"}
          - {label: "Partners", name: "partners", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Body", name: "body", widget: "markdown"}
            ]}
      - file: "hugo/content/stories/_index.md"
        label: "Stories"
        name: "stories"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Show on Home", name: "showonhome", widget: "boolean", default: false}
          - {label: "Header", name: "header", widget: "object", fields: [
              {label: "Background (optional)", name: "background", widget: "image"},
              {label: "Header Text (optional)", name: "hero", widget: "markdown"}
            ]}
          - {label: "Intro", name: "intro", widget: "markdown"}
          - {label: "Heading", name: "heading", widget: "text"}
          - {label: "Button", name: "button", widget: "object", fields: [
              {label: "URL (inc. http://)", name: "url", widget: "string"},
              {label: "Text", name: "text", widget: "string"}
            ]}
  - name: "stories"
    label: "Story"
    editor:
      preview: false
    folder: "hugo/content/stories"
    create: true
    filter: {field: "story", value: "yes"}
    fields:
      - {label: "Story", name: "story", widget: "hidden", default: "yes"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Header", name: "header", widget: "object", fields: [
          {label: "Background (optional)", name: "background", widget: "image"},
          {label: "Header Text (optional)", name: "hero", widget: "markdown"}
        ]}
      - {label: "Summary (Card on Home and Stories)", name: "summary", widget: "object", fields: [
          {label: "Image (Aspect 5by2 - 540px by 216px)", name: "image", widget: "image"},
          {label: "Heading", name: "heading", widget: "string"},
          {label: "Text", name: "text", widget: "string"}
        ]}
      - {label: "Content", name: "content", widget: "object", fields: [
          {label: "Image (Aspect 4by3 - 640px by 480px)", name: "image", widget: "image"},
          {label: "Name", name: "name", widget: "string"},
          {label: "Age", name: "age", widget: "string"},
          {label: "Help received", name: "help", widget: "string"},
          {label: "Body", name: "body", widget: "markdown"}
        ]}
      - {label: "Real change", name: "realchange", widget: "object", fields: [
          {label: "Heading", name: "heading", widget: "string"},
          {label: "Body", name: "body", widget: "markdown"},
          {label: "Button", name: "button", widget: "object", fields: [
            {label: "URL (inc. http://)", name: "url", widget: "string"},
            {label: "Text", name: "text", widget: "string"}
          ]}
        ]}
  - name: "global"
    label: "Global"
    editor:
      preview: false
    files:
      - file: "hugo/content/global/_footer.md"
        label: "Footer"
        name: "footer"
        fields:
          - {label: "Footer Title", name: "title", widget: "string"}
          - {label: "Row 1 (Share)", name: "row1", widget: "markdown"}
          - {label: "Row 2 (Link out)", name: "row2", widget: "markdown"}
          - {label: "Row 3 (Internal link)", name: "row3", widget: "markdown"}
          - {label: "Links", name: "links", widget: "markdown"}
